export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  CHANGE_CURRENCY_INDEX: "CHANGE_CURRENCY_INDEX",
  ADD_TO_CART: "ADD_TO_CART",
  CLOSE_CART_OVERLAY: "CLOSE_CART_OVERLAY",
  OPEN_CART_OVERLAY: "OPEN_CART_OVERLAY",
  CALCULATE: "CALCULATE",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  ADD_ITEM_ID: "ADD_ITEM_ID",
};
