export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  CHANGE_CURRENCY_INDEX: " CHANGE_CURRENCY_INDEX",
};
